name: dora
services:
  dora-metrics:
    image: dora-metrics:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "4040:4040"
    env_file:
    - .env
    restart: unless-stopped